// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:cardabase/feature/cards/card_list_view_options.dart';
import 'package:cardabase/feature/cards/loyalty_card.dart';
import 'package:cardabase/feature/settings/model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AutoBackupSettingsAdapter());
    registerAdapter(BarcodeAdapter());
    registerAdapter(CardListViewOptionsAdapter());
    registerAdapter(DeveloperOptionsAdapter());
    registerAdapter(LoyaltyCardAdapter());
    registerAdapter(LoyaltyCardEffectAdapter());
    registerAdapter(LoyaltyCardEffectSettingsAdapter());
    registerAdapter(SettingsAdapter());
    registerAdapter(SortingStyleAdapter());
    registerAdapter(ThemeSettingsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AutoBackupSettingsAdapter());
    registerAdapter(BarcodeAdapter());
    registerAdapter(CardListViewOptionsAdapter());
    registerAdapter(DeveloperOptionsAdapter());
    registerAdapter(LoyaltyCardAdapter());
    registerAdapter(LoyaltyCardEffectAdapter());
    registerAdapter(LoyaltyCardEffectSettingsAdapter());
    registerAdapter(SettingsAdapter());
    registerAdapter(SortingStyleAdapter());
    registerAdapter(ThemeSettingsAdapter());
  }
}
